name: This is a github action
run-name: this is the run name
on: [push]
jobs: 
  Echo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: echo hello
        run: cat temp.txt
        
